version: '3.1'

services:
  db:
    container_name: sakila-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local_root_password
      MYSQL_DATABASE: sakila
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_user_password
    ports:
      - "3306:3306"
    volumes:
      - sakila-db:/var/lib/mysql

volumes:
  sakila-db: